using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
using UnityEngine;

namespace DevWorkbench.Editor
{
    // ── Creation Service ──────────────────────────────────────────────────────────

    internal static class ManagerCreationService
    {
        private const string GeneratedConfigListFieldName = "_configs";

        public static void CreateManager(ManagerCreatorState state)
        {
            if (state == null || !state.IsValid)
                return;

            var plan = state.BuildPlan();
            CreateManager(plan);
        }

        public static bool TryCreateManagerInParentFolder(string parentAssetPath, string managerName, out string errorMessage)
        {
            var state = new ManagerCreatorState();
            state.SetInputWithParentFolder(parentAssetPath, managerName);
            if (!state.IsValid)
            {
                errorMessage = state.ErrorMessage;
                return false;
            }

            CreateManager(state);
            errorMessage = null;
            return true;
        }

        private static void CreateManager(ManagerCreationPlan plan)
        {
            bool configTypeAvailable = plan.IncludeConfig && FindType(plan.ConfigClassName) != null;

            if (plan.ShouldCreateManagerFile)
                WriteManagerCode(plan);

            EnsureFolder(plan.GeneratedFolderPath);
            WriteManagerPartialGeneratedCode(plan);
            if (plan.IncludeConfig)
            {
                WriteConfigGeneratedCode(plan);
                WriteDataGeneratedCode(plan);
                WriteRefresherCode(plan);
            }

            if (!string.IsNullOrEmpty(plan.EntityFolderPath))
                WriteLeafMarker(plan.EntityFolderPath);

            AssetDatabase.Refresh();

            if (plan.IncludeConfig)
            {
                if (configTypeAvailable)
                    EnsureAssetAndAddressable(plan.ManagerName, plan.AssetFilePath, plan.AddressableAddressName);
                else
                    ManagerPostCompileAssetService.ScheduleAssetCreation(plan);
            }

            ManagerAssetIndex.Invalidate();
        }

        // ── Code writers ──────────────────────────────────────────────────────────

        private static void WriteManagerCode(ManagerCreationPlan plan)
        {
            var builder = new StringBuilder();
            if (plan.IncludeConfig)
                builder.AppendLine("using System.Collections.Generic;");
            builder.AppendLine("using DevWorkbench;");
            builder.AppendLine();
            builder.AppendLine($"public interface {plan.ManagerInterfaceName}");
            builder.AppendLine("{");
            builder.AppendLine();
            builder.AppendLine("}");
            builder.AppendLine();

            if (plan.IncludeConfig)
            {
                builder.AppendLine($"internal sealed partial class {plan.ManagerDataStructName}");
                builder.AppendLine("{");
                builder.AppendLine("    public string Key;");
                builder.AppendLine("}");
                builder.AppendLine();
                builder.AppendLine($"internal sealed partial class {plan.ManagerClassName} : {plan.ManagerInterfaceName}");
                builder.AppendLine("{");
                builder.AppendLine($"    protected override string ConfigAddress => \"{EscapeCSharpStringLiteral(plan.AddressableAddressName)}\";");
                builder.AppendLine($"    private readonly Dictionary<string, {plan.ManagerDataStructName}> _managerDataDict = new();");
                builder.AppendLine("}");
            }
            else
            {
                builder.AppendLine($"internal partial class {plan.ManagerClassName} : {plan.ManagerInterfaceName}");
                builder.AppendLine("{");
                builder.AppendLine();
                builder.Append("}");
            }

            EnsureFolder(Path.GetDirectoryName(plan.ManagerTargetFilePath));
            File.WriteAllText(plan.ManagerTargetFilePath, builder.ToString(), Encoding.UTF8);
        }

        private static void WriteConfigGeneratedCode(ManagerCreationPlan plan)
        {
            if (string.IsNullOrEmpty(plan.GeneratedConfigFilePath)) return;

            var builder = new StringBuilder();
            AppendAutoGeneratedHeader(builder);
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Collections.Generic;");
            builder.AppendLine("using System.Linq;");
            builder.AppendLine("using UnityEngine;");
            builder.AppendLine("using DevWorkbench;");
            builder.AppendLine();
            builder.AppendLine("#if UNITY_EDITOR");
            builder.AppendLine($"public sealed partial class {plan.ConfigClassName}");
            builder.AppendLine("{");
            builder.AppendLine($"    internal List<{plan.ManagerDataStructName}> EditorConfigs => {GeneratedConfigListFieldName};");
            builder.AppendLine("}");
            builder.AppendLine("#endif");
            builder.AppendLine();
            builder.AppendLine($"public sealed partial class {plan.ConfigClassName} : BaseManagerConfig");
            builder.AppendLine("{");
            builder.AppendLine("    [SerializeField]");
            builder.AppendLine($"    private List<{plan.ManagerDataStructName}> {GeneratedConfigListFieldName} = new();");
            builder.AppendLine();
            builder.AppendLine($"    protected override Dictionary<string, BaseManagerData> GetManagerDataDict() => {GeneratedConfigListFieldName}");
            builder.AppendLine("        .Where(static c => !string.IsNullOrWhiteSpace(c.Key))");
            builder.AppendLine("        .ToDictionary(static c => c.Key.Trim(), static c => (BaseManagerData)c, StringComparer.Ordinal);");
            builder.Append("}");

            EnsureFolder(Path.GetDirectoryName(plan.GeneratedConfigFilePath));
            File.WriteAllText(plan.GeneratedConfigFilePath, builder.ToString(), Encoding.UTF8);
        }

        private static void WriteDataGeneratedCode(ManagerCreationPlan plan)
        {
            if (string.IsNullOrEmpty(plan.GeneratedDataFilePath)) return;

            var builder = new StringBuilder();
            AppendAutoGeneratedHeader(builder);
            builder.AppendLine("using System;");
            builder.AppendLine("using DevWorkbench;");
            builder.AppendLine();
            builder.AppendLine("[Serializable]");
            builder.Append($"internal sealed partial class {plan.ManagerDataStructName} : BaseManagerData {{ }}");

            EnsureFolder(Path.GetDirectoryName(plan.GeneratedDataFilePath));
            File.WriteAllText(plan.GeneratedDataFilePath, builder.ToString(), Encoding.UTF8);
        }

        private static void WriteManagerPartialGeneratedCode(ManagerCreationPlan plan)
        {
            if (string.IsNullOrEmpty(plan.GeneratedManagerPartialFilePath)) return;

            var builder = new StringBuilder();
            AppendAutoGeneratedHeader(builder);
            builder.AppendLine("using Cysharp.Threading.Tasks;");
            builder.AppendLine("using DevWorkbench;");
            builder.AppendLine();

            if (plan.IncludeConfig)
            {
                builder.AppendLine($"internal sealed partial class {plan.ManagerClassName} : BaseManager");
                builder.AppendLine("{");
                builder.AppendLine("    protected override async UniTask SetManagerDataDict()");
                builder.AppendLine("    {");
                builder.AppendLine($"        var config = await FrameworkLoader.LoadAsync<{plan.ConfigClassName}>(ConfigAddress);");
                builder.AppendLine("        _managerDataDict.Clear();");
                builder.AppendLine("        foreach (var kv in config.ExportManagerDataDict())");
                builder.AppendLine($"            _managerDataDict[kv.Key] = ({plan.ManagerDataStructName})kv.Value;");
                builder.AppendLine("    }");
                builder.Append("}");
            }
            else
            {
                builder.AppendLine($"internal partial class {plan.ManagerClassName} : BaseManager");
                builder.AppendLine("{");
                builder.AppendLine("    protected override string ConfigAddress => null;");
                builder.AppendLine("    protected override UniTask SetManagerDataDict() => UniTask.CompletedTask;");
                builder.Append("}");
            }

            EnsureFolder(Path.GetDirectoryName(plan.GeneratedManagerPartialFilePath));
            File.WriteAllText(plan.GeneratedManagerPartialFilePath, builder.ToString(), Encoding.UTF8);
        }

        private static void AppendAutoGeneratedHeader(StringBuilder builder)
        {
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("// This file is auto-generated. Do not modify manually.");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine();
        }

        private static void WriteRefresherCode(ManagerCreationPlan plan)
        {
            if (string.IsNullOrEmpty(plan.RefresherFilePath)) return;

            var abs = Path.GetFullPath(Path.Combine(Application.dataPath, "..", plan.RefresherFilePath));
            if (File.Exists(abs)) return;

            var builder = new StringBuilder();
            builder.AppendLine("#if UNITY_EDITOR");
            builder.AppendLine("using UnityEditor;");
            builder.AppendLine("using DevWorkbench;");
            builder.AppendLine();
            builder.AppendLine($"internal sealed class {plan.ManagerName}ManagerRefresher : IManagerRefresher");
            builder.AppendLine("{");
            builder.AppendLine("    public void Refresh(BaseManagerConfig config)");
            builder.AppendLine("    {");
            builder.AppendLine($"        var typed = ({plan.ConfigClassName})config;");
            builder.AppendLine("        var list = typed.EditorConfigs;");
            builder.AppendLine();
            builder.AppendLine("        // TODO: implement the custom refresh logic here.");
            builder.AppendLine();
            builder.AppendLine("        EditorUtility.SetDirty(typed);");
            builder.AppendLine("        AssetDatabase.SaveAssets();");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            builder.Append("#endif");

            EnsureFolder(Path.GetDirectoryName(plan.RefresherFilePath));
            File.WriteAllText(plan.RefresherFilePath, builder.ToString(), Encoding.UTF8);
        }

        // ── Leaf marker（与 Component 目录一致）────────────────────────────────────

        private static void WriteLeafMarker(string entityFolderAssetPath)
        {
            var abs = Path.GetFullPath(
                Path.Combine(Application.dataPath, "..", entityFolderAssetPath, "_leaf.json"));

            var dir = Path.GetDirectoryName(abs);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            if (!File.Exists(abs))
                File.WriteAllText(abs, string.Empty);
        }

        // ── Asset & Addressable ─────────────────────────────────────────────────

        internal static void EnsureAssetAndAddressable(string managerName, string assetPath, string assetAddress)
        {
            var asset = AssetDatabase.LoadAssetAtPath<ScriptableObject>(assetPath);
            if (asset == null)
            {
                EnsureFolder(Path.GetDirectoryName(assetPath));

                var configType = FindType($"{managerName}ManagerConfig");
                if (configType == null)
                {
                    Debug.LogError($"[ManagerCreationService] Config type not found: {managerName}ManagerConfig");
                    return;
                }

                asset = ScriptableObject.CreateInstance(configType);
                AssetDatabase.CreateAsset(asset, assetPath);
                AssetDatabase.SaveAssets();
            }

            var settings = AddressableAssetSettingsDefaultObject.Settings;
            if (settings == null)
            {
                Debug.LogWarning("[ManagerCreationService] AddressableAssetSettings not found; skipping Addressables configuration.");
                return;
            }

            var groupName = ManagerCreatorState.AddressableGroupName;
            var group = settings.groups.FirstOrDefault(g => g != null && g.Name == groupName)
                ?? settings.CreateGroup(groupName, false, false, true, null);
            var guid = AssetDatabase.AssetPathToGUID(assetPath);
            var entry = settings.CreateOrMoveEntry(guid, group);
            entry.address = assetAddress;
            settings.SetDirty(AddressableAssetSettings.ModificationEvent.EntryMoved, entry, true);

            AssetDatabase.SaveAssets();
            ManagerAssetIndex.Invalidate();
            Debug.Log($"[ManagerCreationService] {managerName}Manager created successfully.");
        }

        private static Type FindType(string typeName)
        {
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                try
                {
                    var t = assembly.GetType(typeName);
                    if (t != null) return t;
                }
                catch { }
            }
            return null;
        }

        // ── Folder utility (inline) ───────────────────────────────────────────────

        private static string EscapeCSharpStringLiteral(string value)
        {
            if (string.IsNullOrEmpty(value)) return string.Empty;
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        internal static void EnsureFolder(string assetPath)
        {
            if (string.IsNullOrEmpty(assetPath)) return;
            assetPath = assetPath.Replace('\\', '/').TrimEnd('/');
            if (assetPath == "Assets" || AssetDatabase.IsValidFolder(assetPath)) return;

            var parts = assetPath.Split('/');
            for (var i = 1; i < parts.Length; i++)
            {
                var parent = string.Join("/", parts, 0, i);
                var child = $"{parent}/{parts[i]}";
                if (!AssetDatabase.IsValidFolder(child))
                    AssetDatabase.CreateFolder(parent, parts[i]);
            }
        }
    }

    // ── Post-Compile Asset Service ────────────────────────────────────────────────

    internal static class ManagerPostCompileAssetService
    {
        [InitializeOnLoadMethod]
        private static void ProcessPendingAssetCreation()
        {
            var managerName = SessionState.GetString(ManagerCreatorState.SessionManagerNameKey, string.Empty);
            var assetPath = SessionState.GetString(ManagerCreatorState.SessionAssetPathKey, string.Empty);
            var assetAddress = SessionState.GetString(ManagerCreatorState.SessionAssetAddressKey, string.Empty);

            if (string.IsNullOrEmpty(managerName) || string.IsNullOrEmpty(assetPath) || string.IsNullOrEmpty(assetAddress))
                return;

            SessionState.EraseString(ManagerCreatorState.SessionManagerNameKey);
            SessionState.EraseString(ManagerCreatorState.SessionAssetPathKey);
            SessionState.EraseString(ManagerCreatorState.SessionAssetAddressKey);

            EditorApplication.delayCall += () =>
                ManagerCreationService.EnsureAssetAndAddressable(managerName, assetPath, assetAddress);
        }

        public static void ScheduleAssetCreation(ManagerCreationPlan plan)
        {
            SessionState.SetString(ManagerCreatorState.SessionManagerNameKey, plan.ManagerName);
            SessionState.SetString(ManagerCreatorState.SessionAssetPathKey, plan.AssetFilePath);
            SessionState.SetString(ManagerCreatorState.SessionAssetAddressKey, plan.AddressableAddressName);
        }
    }

    // ── Asset Index ───────────────────────────────────────────────────────────────

    internal static class ManagerAssetIndex
    {
        private static Dictionary<string, string> _scripts;
        private static Dictionary<string, string> _assets;

        static ManagerAssetIndex()
        {
            EditorApplication.projectChanged -= Invalidate;
            EditorApplication.projectChanged += Invalidate;
        }

        public static string FindManagerScript(string fileName) =>
            Find(ref _scripts, ManagerCreatorState.RootAssetPath, fileName, ".cs");

        public static string FindManagerAsset(string fileName) =>
            Find(ref _assets, ManagerCreatorState.RootAssetPath, fileName, ".asset");

        public static void Invalidate()
        {
            _scripts = null;
            _assets = null;
        }

        private static string Find(ref Dictionary<string, string> cache, string root, string fileName, string ext)
        {
            if (string.IsNullOrEmpty(fileName)) return null;
            cache ??= BuildIndex(root, ext);
            return cache.TryGetValue(fileName, out var path) ? path : null;
        }

        private static Dictionary<string, string> BuildIndex(string root, string ext)
        {
            var map = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (var guid in AssetDatabase.FindAssets(string.Empty, new[] { root }))
            {
                var path = AssetDatabase.GUIDToAssetPath(guid)?.Replace('\\', '/');
                if (string.IsNullOrEmpty(path) || !path.EndsWith(ext, StringComparison.OrdinalIgnoreCase))
                    continue;
                var name = Path.GetFileName(path);
                if (!map.ContainsKey(name)) map.Add(name, path);
            }
            return map;
        }
    }
}
