using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
using UnityEngine;

namespace DevWorkbench.Editor
{
    internal static class ComponentCreationService
    {
        private const string ConfigListField = "_configs";

        public static void Execute(ComponentCreatorState state)
        {
            if (state == null || !state.IsValid) return;
            Execute(state.BuildPlan());
        }

        private static void Execute(ComponentCreationPlan plan)
        {
            bool configTypeAvailable = FindType(plan.ConfigClassName) != null;

            if (plan.ShouldCreateComponentFile) WriteComponentCode(plan);

            EnsureFolder(plan.GeneratedFolderPath);
            WriteConfigGeneratedCode(plan);
            WriteDataGeneratedCode(plan);
            WriteComponentPartialGeneratedCode(plan);

            if (!string.IsNullOrEmpty(plan.EntityFolderPath))
                WriteLeafMarker(plan.EntityFolderPath);

            AssetDatabase.Refresh();

            if (configTypeAvailable)
                EnsureAssetAndAddressable(plan.ComponentName, plan.AssetFilePath, plan.AddressableAddress);
            else
                ComponentPostCompileAssetService.Schedule(plan);

            ComponentAssetIndex.Invalidate();
        }

        private static void WriteComponentCode(ComponentCreationPlan plan)
        {
            var sb = new StringBuilder();
            sb.AppendLine("using DevWorkbench;");
            sb.AppendLine();
            sb.AppendLine($"public sealed partial class {plan.ComponentDataClassName}");
            sb.AppendLine("{");
            sb.AppendLine("    public string Key;");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine($"public sealed partial class {plan.ComponentClassName}");
            sb.AppendLine("{");
            sb.AppendLine($"    private readonly {plan.ComponentDataClassName} _componentData;");
            sb.AppendLine("}");

            EnsureFolder(Path.GetDirectoryName(plan.ComponentFilePath));
            File.WriteAllText(plan.ComponentFilePath, sb.ToString(), Encoding.UTF8);
        }

        private static void WriteConfigGeneratedCode(ComponentCreationPlan plan)
        {
            if (string.IsNullOrEmpty(plan.GeneratedConfigFilePath)) return;

            var f = ConfigListField;
            var cc = plan.ComponentClassName;
            var dc = plan.ComponentDataClassName;
            var cfg = plan.ConfigClassName;

            var sb = new StringBuilder();
            AppendAutoGeneratedHeader(sb);
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using DevWorkbench;");
            sb.AppendLine();
            sb.AppendLine($"public sealed partial class {cfg} : BaseComponentConfig");
            sb.AppendLine("{");
            sb.AppendLine("    [SerializeField]");
            sb.AppendLine($"    private List<{dc}> {f} = new();");
            sb.AppendLine();
            sb.AppendLine($"    public override Type ConfigItemType => typeof({dc});");
            sb.AppendLine($"    public override IList GetConfigList() => {f};");
            sb.AppendLine();
            sb.AppendLine($"    protected override Dictionary<string, BaseComponentData> GetComponentDataDict() => {f}");
            sb.AppendLine("        .Where(config => !string.IsNullOrWhiteSpace(config.Key))");
            sb.AppendLine($"        .ToDictionary(config => $\"{cc}_{{config.Key.Trim()}}\", config => (BaseComponentData)config);");
            sb.AppendLine("}");

            EnsureFolder(Path.GetDirectoryName(plan.GeneratedConfigFilePath));
            File.WriteAllText(plan.GeneratedConfigFilePath, sb.ToString(), Encoding.UTF8);
        }

        private static void WriteDataGeneratedCode(ComponentCreationPlan plan)
        {
            if (string.IsNullOrEmpty(plan.GeneratedDataFilePath)) return;

            var cc = plan.ComponentClassName;
            var dc = plan.ComponentDataClassName;

            var sb = new StringBuilder();
            AppendAutoGeneratedHeader(sb);
            sb.AppendLine("using System;");
            sb.AppendLine("using DevWorkbench;");
            sb.AppendLine();
            sb.AppendLine("[Serializable]");
            sb.AppendLine($"public sealed partial class {dc} : BaseComponentData");
            sb.AppendLine("{");
            sb.AppendLine($"    protected override BaseComponent CreateComponent() => new {cc}(({dc})MemberwiseClone());");
            sb.AppendLine("}");

            EnsureFolder(Path.GetDirectoryName(plan.GeneratedDataFilePath));
            File.WriteAllText(plan.GeneratedDataFilePath, sb.ToString(), Encoding.UTF8);
        }

        private static void WriteComponentPartialGeneratedCode(ComponentCreationPlan plan)
        {
            if (string.IsNullOrEmpty(plan.GeneratedComponentPartialFilePath)) return;

            var cc = plan.ComponentClassName;
            var dc = plan.ComponentDataClassName;

            var sb = new StringBuilder();
            AppendAutoGeneratedHeader(sb);
            sb.AppendLine("using DevWorkbench;");
            sb.AppendLine();
            sb.AppendLine($"public sealed partial class {cc} : BaseComponent");
            sb.AppendLine("{");
            sb.AppendLine($"    public {cc}({dc} componentData)");
            sb.AppendLine("    {");
            sb.AppendLine("        _ = _componentData;");
            sb.AppendLine("        _componentData = componentData;");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            EnsureFolder(Path.GetDirectoryName(plan.GeneratedComponentPartialFilePath));
            File.WriteAllText(plan.GeneratedComponentPartialFilePath, sb.ToString(), Encoding.UTF8);
        }

        private static void AppendAutoGeneratedHeader(StringBuilder sb)
        {
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is auto-generated. Do not modify manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
        }

        private static void WriteLeafMarker(string entityFolderAssetPath)
        {
            var abs = Path.GetFullPath(
                Path.Combine(Application.dataPath, "..", entityFolderAssetPath, "_leaf.json"));

            var dir = Path.GetDirectoryName(abs);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            if (!File.Exists(abs))
                File.WriteAllText(abs, string.Empty);
        }

        internal static bool EnsureAssetAndAddressable(string componentName, string assetPath, string assetAddress)
        {
            var asset = AssetDatabase.LoadAssetAtPath<ScriptableObject>(assetPath);
            if (asset == null)
            {
                EnsureFolder(Path.GetDirectoryName(assetPath));

                var configType = FindType($"{componentName}ComponentConfig");
                if (configType == null)
                {
                    Debug.LogError($"[ComponentCreationService] Config type not found: {componentName}ComponentConfig");
                    return false;
                }

                asset = ScriptableObject.CreateInstance(configType);
                AssetDatabase.CreateAsset(asset, assetPath);

                if (asset is BaseComponentConfig newConfig)
                    InjectDefaultEntry(newConfig);

                AssetDatabase.SaveAssets();
            }

            var settings = AddressableAssetSettingsDefaultObject.Settings;
            if (settings == null)
            {
                Debug.LogWarning("[ComponentCreationService] AddressableAssetSettings not found; skipping Addressables configuration.");
                return false;
            }

            var groupName = ComponentCreatorState.AddressableGroupName;
            var group = settings.groups.FirstOrDefault(g => g != null && g.Name == groupName)
                ?? settings.CreateGroup(groupName, false, false, true, null);
            var guid = AssetDatabase.AssetPathToGUID(assetPath);
            var entry = settings.CreateOrMoveEntry(guid, group);
            entry.address = assetAddress;
            settings.SetDirty(AddressableAssetSettings.ModificationEvent.EntryMoved, entry, true);

            AssetDatabase.SaveAssets();
            ComponentAssetIndex.Invalidate();
            Debug.Log($"[ComponentCreationService] {componentName}Component created successfully.");
            return true;
        }

        private static void InjectDefaultEntry(BaseComponentConfig config)
        {
            var list = config.GetConfigList();
            var itemType = config.ConfigItemType;
            if (list == null || itemType == null) return;

            var item = Activator.CreateInstance(itemType);
            var keyField = itemType.GetField("Key", BindingFlags.Public | BindingFlags.Instance);
            keyField?.SetValue(item, "default");
            list.Add(item);
            EditorUtility.SetDirty(config);
        }

        private static Type FindType(string typeName)
        {
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                try
                {
                    foreach (var t in assembly.GetTypes())
                        if (t.Name == typeName) return t;
                }
                catch (ReflectionTypeLoadException e)
                {
                    foreach (var t in e.Types)
                        if (t != null && t.Name == typeName) return t;
                }
                catch { }
            }
            return null;
        }

        internal static void EnsureFolder(string assetPath)
        {
            if (string.IsNullOrEmpty(assetPath)) return;
            assetPath = assetPath.Replace('\\', '/').TrimEnd('/');
            if (assetPath == "Assets" || AssetDatabase.IsValidFolder(assetPath)) return;

            var parts = assetPath.Split('/');
            for (var i = 1; i < parts.Length; i++)
            {
                var parent = string.Join("/", parts, 0, i);
                var child = $"{parent}/{parts[i]}";
                if (!AssetDatabase.IsValidFolder(child))
                    AssetDatabase.CreateFolder(parent, parts[i]);
            }
        }
    }

    internal static class ComponentPostCompileAssetService
    {
        [InitializeOnLoadMethod]
        private static void OnLoad()
        {
            var name = SessionState.GetString(ComponentCreatorState.SessionComponentNameKey, string.Empty);
            var path = SessionState.GetString(ComponentCreatorState.SessionAssetPathKey, string.Empty);
            var address = SessionState.GetString(ComponentCreatorState.SessionAssetAddressKey, string.Empty);

            if (string.IsNullOrEmpty(name) || string.IsNullOrEmpty(path) || string.IsNullOrEmpty(address))
                return;

            SessionState.EraseString(ComponentCreatorState.SessionComponentNameKey);
            SessionState.EraseString(ComponentCreatorState.SessionAssetPathKey);
            SessionState.EraseString(ComponentCreatorState.SessionAssetAddressKey);

            EditorApplication.delayCall += () =>
                ComponentCreationService.EnsureAssetAndAddressable(name, path, address);
        }

        public static void Schedule(ComponentCreationPlan plan)
        {
            SessionState.SetString(ComponentCreatorState.SessionComponentNameKey, plan.ComponentName);
            SessionState.SetString(ComponentCreatorState.SessionAssetPathKey, plan.AssetFilePath);
            SessionState.SetString(ComponentCreatorState.SessionAssetAddressKey, plan.AddressableAddress);
        }
    }

    internal static class ComponentAssetIndex
    {
        private static Dictionary<string, string> _scripts;
        private static Dictionary<string, string> _assets;

        static ComponentAssetIndex()
        {
            EditorApplication.projectChanged -= Invalidate;
            EditorApplication.projectChanged += Invalidate;
        }

        public static string FindComponentScript(string fileName) =>
            Find(ref _scripts, ComponentCreatorState.RootAssetPath, fileName, ".cs");

        public static string FindComponentAsset(string fileName) =>
            Find(ref _assets, ComponentCreatorState.RootAssetPath, fileName, ".asset");

        public static void Invalidate()
        {
            _scripts = null;
            _assets = null;
        }

        private static string Find(ref Dictionary<string, string> cache, string root, string fileName, string ext)
        {
            if (string.IsNullOrEmpty(fileName)) return null;
            cache ??= BuildIndex(root, ext);
            return cache.TryGetValue(fileName, out var path) ? path : null;
        }

        private static Dictionary<string, string> BuildIndex(string root, string ext)
        {
            var map = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (var guid in AssetDatabase.FindAssets(string.Empty, new[] { root }))
            {
                var path = AssetDatabase.GUIDToAssetPath(guid)?.Replace('\\', '/');
                if (string.IsNullOrEmpty(path) || !path.EndsWith(ext, StringComparison.OrdinalIgnoreCase))
                    continue;
                var name = Path.GetFileName(path);
                if (!map.ContainsKey(name)) map.Add(name, path);
            }
            return map;
        }
    }
}
